### ISSUE TITLE
longsleep/golang-backports problem

### ISSUE THREAD

**Issue by vavepl** [SaifRehman/IBMCLOUD-Ethereum-Blockchain#1]
Step 5/17 : RUN add-apt-repository ppa:longsleep/golang-backports
 ---> Running in 60ace4c1e664
 Golang 1.8, 1.9 and 1.10 PPA for Ubuntu 16.04 Xenial
 More info: https://launchpad.net/~longsleep/+archive/ubuntu/golang-backports
Ign:1 http://ppa.launchpad.net/longsleep/golang-backports/ubuntu bionic InRelease
Hit:2 http://security.ubuntu.com/ubuntu bionic-security InRelease
Err:3 http://ppa.launchpad.net/longsleep/golang-backports/ubuntu bionic Release
  404  Not Found [IP: 91.189.95.83 80]
Hit:4 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:5 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:6 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
Reading package lists...
E: The repository 'http://ppa.launchpad.net/longsleep/golang-backports/ubuntu bionic Release' does not have a Release file.
The command '/bin/sh -c add-apt-repository ppa:longsleep/golang-backports' returned a non-zero code: 100

**Comment by SaifRehman** [comment]
what is the exact issue you are facing?

**Comment by vavepl** [comment]
I can't build docker image because of this error

**Comment by vavepl** [comment]
i commented this line and now its work.

**Comment by SaifRehman** [comment]
let me check

**Comment by SaifRehman** [comment]
can you give a pull request

**Comment by vavepl** [comment]
The error is probably due to recent updates, because using ubuntu:latest can always jump out some error, it would have to be fixed version (statically) and then the config would work correctly, who knows what will be for a few months: P

**Comment by SaifRehman** [comment]
are you trying to deploy to IBM Cloud?

**Comment by vavepl** [comment]
I'm checking your guide :)

**Comment by SaifRehman** [comment]
great, there is a helm chart created. better use that
